/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Category,
  Category$inboundSchema,
  Category$Outbound,
  Category$outboundSchema,
} from "./category.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Tag,
  Tag$inboundSchema,
  Tag$Outbound,
  Tag$outboundSchema,
} from "./tag.js";

/**
 * pet status in the store
 */
export const PetStatus = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * pet status in the store
 */
export type PetStatus = ClosedEnum<typeof PetStatus>;

export type Pet = {
  id?: number | undefined;
  name: string;
  category?: Category | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag> | undefined;
  /**
   * pet status in the store
   */
  status?: PetStatus | undefined;
};

/** @internal */
export const PetStatus$inboundSchema: z.ZodNativeEnum<typeof PetStatus> = z
  .nativeEnum(PetStatus);
/** @internal */
export const PetStatus$outboundSchema: z.ZodNativeEnum<typeof PetStatus> =
  PetStatus$inboundSchema;

/** @internal */
export const Pet$inboundSchema: z.ZodType<Pet, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    name: z.string(),
    category: Category$inboundSchema.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(Tag$inboundSchema).optional(),
    status: PetStatus$inboundSchema.optional(),
  });
/** @internal */
export type Pet$Outbound = {
  id?: number | undefined;
  name: string;
  category?: Category$Outbound | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag$Outbound> | undefined;
  status?: string | undefined;
};

/** @internal */
export const Pet$outboundSchema: z.ZodType<Pet$Outbound, z.ZodTypeDef, Pet> = z
  .object({
    id: z.number().int().optional(),
    name: z.string(),
    category: Category$outboundSchema.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(Tag$outboundSchema).optional(),
    status: PetStatus$outboundSchema.optional(),
  });

export function petToJSON(pet: Pet): string {
  return JSON.stringify(Pet$outboundSchema.parse(pet));
}
export function petFromJSON(
  jsonString: string,
): SafeParseResult<Pet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pet' from JSON`,
  );
}
